title = "Seb Pretzer"
description = ""
default_language = "en"

base_url = "https://pretzer.io"

compile_sass = true
build_search_index = false

theme = "hermit_zola"

[markdown]
highlight_code = false

[extra]
home_subtitle = "Exploring the magic of computers"

hermit_menu = [
    { link = "/about", name = "About" },
]
hermit_social = [
    { name = "linkedin", link = "https://www.linkedin.com/in/pretzer"},
    { name = "github", link = "https://github.com/sebpretzer" },
    { name = "email", link = "mailto:hi@pretzer.io" },
]

[extra.highlightjs]
enable = true
clipboard = true
theme = "base16-onedark"


[extra.author]
name = "Seb Pretzer"
email = "hi@pretzer.io"
